description = "This is my new Hugo FixIt site"
keywords = ["Hugo", "FixIt"]

[author]
name = "eebond"
email = "eebond0327@gmail.com"
link = "https://github.com/eebond/"
avatar = "/images/avatar.jpg"

[app]
title = "EEBONDの博客"

[header]

[header.title]
logo = "/images/favicon.png"

[home]

[home.profile]
enable = true

[customPartials]
head = [
  "inject/fixit-docs-bookmark.html",
]
